In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split # used for splitting training and testing data
from sklearn.metrics import confusion_matrix
from sklearn.utils.class_weight import compute_class_weight

torch.manual_seed(1)

In [2]:
plt.figure(figsize=(8,5))

# time steps per batch of data
seq_length = 100

time_steps = np.linspace(0, np.pi, seq_length + 1)

data = pd.read_csv('../Datasets/SectionData.csv')

x = data.iloc[:, :-1].values
y = data.iloc[:, -1].values

<Figure size 576x360 with 0 Axes>

In [3]:
class NeuralNetwork(nn.Module):
    def __init__(self, input_size, kernel_size, hidden_size, drop_prob):
        super(NeuralNetwork, self).__init__()
        self.model = nn.Sequential(
            nn.Conv1d(1, 1, kernel_size),
            nn.Flatten(),
            #nn.ReLU(),
            nn.Dropout(drop_prob),
            nn.Linear(input_size - kernel_size + 1, hidden_size[0]),
            nn.Linear(hidden_size[0], hidden_size[1]),
            nn.Linear(hidden_size[1], hidden_size[2]),
            #nn.LogSoftmax(dim=1), # NLLLoss
            nn.Softmax(dim=1) # MSELoss
        )
        #self.conv1 = nn.Conv1d(1, 1, kernel_size)
        #self.flat = nn.Flatten()
        #self.relu = nn.ReLU()
        #self.dropout = nn.Dropout(drop_prob)
        #self.fc1 = nn.Linear(input_size - kernel_size + 1, hidden_size[0])
        #self.fc2 = nn.Linear(hidden_size[0], hidden_size[1])
        #self.fc3 = nn.Linear(hidden_size[1], hidden_size[2])
        #self.softmax = nn.Softmax(dim=1)
        
    def forward(self, x):
        #print("X: " + str(x.shape))
        #out1 = self.conv1(x)
        #print("Out1: " + str(out1.size()))
        #outF = self.flat(out1)
        #print("OutF: " + str(out1.size()))
        #out2 = self.relu(outF)
        #print("Out2: " + str(out2.size()))
        #out3 = self.dropout(out2)
        #print("Out3: " + str(out3.size()))
        #out4 = self.fc1(out3)
        #print("Out4: " + str(out4.size()))
        #out5 = self.fc2(out4)
        #print("Out5: " + str(out5.size()))
        #out6 = self.fc3(out5)
        #print("Out6: " + str(out6.size()))
        #print(out6)
        #out7 = self.softmax(out6)
        #print("Out7: " + str(out7.size()))
        #print(out7)    
        
        out = self.model(x)
        
        return out

In [4]:
BEAT_TYPES_INDEX = {
    'N': 0,
    'L': 1,
    'R': 2,
    'A': 3,
    'V': 4,
    'F': 5,
}

def formatDataX(data):
    temp = torch.tensor(data).float()
    return temp.view(temp.size(0), 1, temp.size(1))

def formatDataY(data):
    return torch.tensor(data).float()

def preprocess(df):

    # drop ecgNum row
    df = df.drop(["ecgNum"], axis=1)
    # Classify the dependent and independent variables
    X = df.iloc[:, :-1].values
    labels = df.iloc[:, -1].values
    Y = np.array([np.insert(np.zeros(5), BEAT_TYPES_INDEX[label], 1) for label in labels])
    
    # split the data into train, validate, test
    X_temp, X_test, Y_temp, Y_test = train_test_split(X, Y, test_size=0.2, random_state=0)
    X_train, X_val, Y_train, Y_val = train_test_split(X_temp, Y_temp, test_size=0.2, random_state=0)
    
    class_weights = compute_class_weight('balanced', ['N','L','R','A','V','F'], labels)
    
    return formatDataX(X_train), formatDataX(X_val), formatDataX(X_test), formatDataY(Y_train), formatDataY(Y_val), formatDataY(Y_test), formatDataY(class_weights)


In [5]:
#X_train, X_val, X_test, Y_train, Y_val, Y_test, weights = preprocess(data)
#print(X_train.size())
#print(X_val.size())
#print(X_test.size())
#print(Y_train.size())
#print(Y_val.size())
#print(Y_test.size())

In [6]:
# size of the input at each time step
# TODO: handle input sizes
input_size = 200
# kernel size
kernel_size = 20
# size of the hidden state and cell state at each time step
hidden_size = [64, 32, 6]
# dropout probability
drop_prob = 0.2

# instantiate the NN
neuralNet = NeuralNetwork(input_size, kernel_size, hidden_size, drop_prob)
print(neuralNet)

NeuralNetwork(
  (model): Sequential(
    (0): Conv1d(1, 1, kernel_size=(20,), stride=(1,))
    (1): Flatten()
    (2): Dropout(p=0.2, inplace=False)
    (3): Linear(in_features=181, out_features=64, bias=True)
    (4): Linear(in_features=64, out_features=32, bias=True)
    (5): Linear(in_features=32, out_features=6, bias=True)
    (6): Softmax(dim=1)
  )
)


In [7]:
# Mean Squared Error and Adam Optimizer with a learning rate of 0.01
# TODO: play with LR
#criterion = nn.MSELoss()
#optimizer = optim.SGD(net.parameters(), lr=0.01)
#optimizer = torch.optim.Adam(neuralNet.parameters(), lr=0.01)

In [8]:
epochs = 100
print_every = 45

X_train, X_val, X_test, Y_train, Y_val, Y_test, weights = preprocess(data)

In [9]:
# train the NN
def train(net, X, Y, num_epochs, weights):  
    #criterion = nn.NLLLoss(weights) 
    criterion = nn.MSELoss()
    
    #optimizer = optim.SGD(net.parameters(), lr=0.01)
    optimizer = torch.optim.Adam(net.parameters(), lr=0.01)
    
    for epoch in range (num_epochs):
        optimizer.zero_grad()
        out = net(X)
        
        # NLLLoss
        # actValues, actIndices = torch.max(Y, 1)
        #loss = criterion(out, actIndices)
        
        # MSELoss
        loss = criterion(out, Y)
        
        loss.backward()
        optimizer.step()
        
        print("Epoch {} of {} => Loss {:.4f}\r".format(epoch, num_epochs, loss.item()), end="")

    return net

In [10]:
trained_NN = train(neuralNet, X_train, Y_train, epochs, weights)

In [11]:
def test(net, X, Y):
    resValues, resIndices = torch.max(net(X), 1)
    length = len(resIndices.numpy())
    testValues, testIndices = torch.max(Y, 1)
    results = np.array([np.insert(np.zeros(5), index, 1) for index in resIndices])
    
    conf_matrix = confusion_matrix(resIndices.numpy(), testIndices.numpy())

    correct = 0
    for i in range(len(conf_matrix)):
        correct += conf_matrix[i,i]
        
    print("Accuracy: {:.2%}".format(correct/length))
    
    print("\nConfusion Matrix:")
    print(conf_matrix)

In [12]:
#test(trained_NN, X_train, Y_train)
test(trained_NN, X_test, Y_test)
#test(trained_NN, X_val, Y_val)

Accuracy: 83.12%

Confusion Matrix:
[[14898  1139   541   266   558   146]
 [   11   278     2    23    39     0]
 [   44    17   898   121    41     0]
 [   16   192     3    33    96     8]
 [   76     5     2    46   601     1]
 [    0     0     0     0     0     0]]


In [14]:
torch.save(trained_NN, "../Models/TestingCNN.pt")